// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package toyotaid is a generated GoMock package.
package toyotaid

import (
	context "context"
	reflect "reflect"

	toyotaid "github.com/arraisi/hcm-be/internal/domain/dto/toyotaid"
	gomock "github.com/golang/mock/gomock"
)

// MockIdempotencyService is a mock of IdempotencyService interface.
type MockIdempotencyService struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyServiceMockRecorder
}

// MockIdempotencyServiceMockRecorder is the mock recorder for MockIdempotencyService.
type MockIdempotencyServiceMockRecorder struct {
	mock *MockIdempotencyService
}

// NewMockIdempotencyService creates a new mock instance.
func NewMockIdempotencyService(ctrl *gomock.Controller) *MockIdempotencyService {
	mock := &MockIdempotencyService{ctrl: ctrl}
	mock.recorder = &MockIdempotencyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyService) EXPECT() *MockIdempotencyServiceMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockIdempotencyService) Exists(eventID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", eventID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockIdempotencyServiceMockRecorder) Exists(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIdempotencyService)(nil).Exists), eventID)
}

// Store mocks base method.
func (m *MockIdempotencyService) Store(eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockIdempotencyServiceMockRecorder) Store(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockIdempotencyService)(nil).Store), eventID)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateToyotaID mocks base method.
func (m *MockService) CreateToyotaID(ctx context.Context, request toyotaid.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToyotaID", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToyotaID indicates an expected call of CreateToyotaID.
func (mr *MockServiceMockRecorder) CreateToyotaID(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToyotaID", reflect.TypeOf((*MockService)(nil).CreateToyotaID), ctx, request)
}
