// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package engine is a generated GoMock package.
package engine

import (
	context "context"
	reflect "reflect"

	domain "github.com/arraisi/hcm-be/internal/domain"
	customervehicle "github.com/arraisi/hcm-be/internal/domain/dto/customervehicle"
	roleads "github.com/arraisi/hcm-be/internal/domain/dto/roleads"
	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
)

// MockCustomerVehicleService is a mock of CustomerVehicleService interface.
type MockCustomerVehicleService struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerVehicleServiceMockRecorder
}

// MockCustomerVehicleServiceMockRecorder is the mock recorder for MockCustomerVehicleService.
type MockCustomerVehicleServiceMockRecorder struct {
	mock *MockCustomerVehicleService
}

// NewMockCustomerVehicleService creates a new mock instance.
func NewMockCustomerVehicleService(ctrl *gomock.Controller) *MockCustomerVehicleService {
	mock := &MockCustomerVehicleService{ctrl: ctrl}
	mock.recorder = &MockCustomerVehicleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerVehicleService) EXPECT() *MockCustomerVehicleServiceMockRecorder {
	return m.recorder
}

// GetCustomerVehiclePaginated mocks base method.
func (m *MockCustomerVehicleService) GetCustomerVehiclePaginated(ctx context.Context, req customervehicle.GetCustomerVehiclePaginatedRequest) ([]domain.CustomerVehicle, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerVehiclePaginated", ctx, req)
	ret0, _ := ret[0].([]domain.CustomerVehicle)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCustomerVehiclePaginated indicates an expected call of GetCustomerVehiclePaginated.
func (mr *MockCustomerVehicleServiceMockRecorder) GetCustomerVehiclePaginated(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerVehiclePaginated", reflect.TypeOf((*MockCustomerVehicleService)(nil).GetCustomerVehiclePaginated), ctx, req)
}

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockTransactionRepository) BeginTransaction(ctx context.Context) (*sqlx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx)
	ret0, _ := ret[0].(*sqlx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockTransactionRepositoryMockRecorder) BeginTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).BeginTransaction), ctx)
}

// CommitTransaction mocks base method.
func (m *MockTransactionRepository) CommitTransaction(tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CommitTransaction(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CommitTransaction), tx)
}

// RollbackTransaction mocks base method.
func (m *MockTransactionRepository) RollbackTransaction(tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTransaction", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTransaction indicates an expected call of RollbackTransaction.
func (mr *MockTransactionRepositoryMockRecorder) RollbackTransaction(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).RollbackTransaction), tx)
}

// MockRoLeadsRepository is a mock of RoLeadsRepository interface.
type MockRoLeadsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoLeadsRepositoryMockRecorder
}

// MockRoLeadsRepositoryMockRecorder is the mock recorder for MockRoLeadsRepository.
type MockRoLeadsRepositoryMockRecorder struct {
	mock *MockRoLeadsRepository
}

// NewMockRoLeadsRepository creates a new mock instance.
func NewMockRoLeadsRepository(ctrl *gomock.Controller) *MockRoLeadsRepository {
	mock := &MockRoLeadsRepository{ctrl: ctrl}
	mock.recorder = &MockRoLeadsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoLeadsRepository) EXPECT() *MockRoLeadsRepositoryMockRecorder {
	return m.recorder
}

// CreateRoLeads mocks base method.
func (m *MockRoLeadsRepository) CreateRoLeads(ctx context.Context, tx *sqlx.Tx, req []domain.RoLeads) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoLeads", ctx, tx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoLeads indicates an expected call of CreateRoLeads.
func (mr *MockRoLeadsRepositoryMockRecorder) CreateRoLeads(ctx, tx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoLeads", reflect.TypeOf((*MockRoLeadsRepository)(nil).CreateRoLeads), ctx, tx, req)
}

// DeleteRoLeads mocks base method.
func (m *MockRoLeadsRepository) DeleteRoLeads(ctx context.Context, tx *sqlx.Tx, req domain.RoLeads) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoLeads", ctx, tx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoLeads indicates an expected call of DeleteRoLeads.
func (mr *MockRoLeadsRepositoryMockRecorder) DeleteRoLeads(ctx, tx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoLeads", reflect.TypeOf((*MockRoLeadsRepository)(nil).DeleteRoLeads), ctx, tx, req)
}

// GetRoLeads mocks base method.
func (m *MockRoLeadsRepository) GetRoLeads(ctx context.Context, req roleads.GetRoLeadsRequest) (domain.RoLeads, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoLeads", ctx, req)
	ret0, _ := ret[0].(domain.RoLeads)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoLeads indicates an expected call of GetRoLeads.
func (mr *MockRoLeadsRepositoryMockRecorder) GetRoLeads(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoLeads", reflect.TypeOf((*MockRoLeadsRepository)(nil).GetRoLeads), ctx, req)
}
