CREATE TABLE dbo.tm_customer_vehicle
(
    i_id                        VARCHAR(36) NOT NULL,
    i_customer_id               VARCHAR(36) NOT NULL,
    i_one_account_id            VARCHAR(36) NULL,
    c_vin                       VARCHAR(17) NULL,
    c_police_number             VARCHAR(16) NULL,
    c_katashiki_suffix          VARCHAR(64) NULL,
    c_color_code                VARCHAR(16) NULL,
    c_model                     VARCHAR(64) NULL,
    c_variant                   VARCHAR(128) NULL,
    n_color                     VARCHAR(64) NULL,
    v_actual_mileage            INT NULL,
    c_vehicle_category          VARCHAR(10) NULL,
    c_stnk_number               VARCHAR(32) NULL,
    n_stnk_name                 VARCHAR(64) NULL,
    d_stnk_expiry_date          DATETIME NULL,
    e_stnk_address              VARCHAR(256) NULL,
    e_stnk_image                VARBINARY(MAX) NULL,
    e_invoice_file              VARBINARY(MAX) NULL,
    b_main_vehicle_flag         BIT NULL,
    v_distance_travelled        INT NULL,
    c_customer_type             VARCHAR(32) NULL,
    c_primary_user              VARCHAR(6) NULL,
    c_digital_catalog_flag      BIT NULL,
    c_order_number_tco          VARCHAR(17) NULL,
    c_customer_interest_to_care VARCHAR(32) NULL,
    c_customer_interest_to_buy  VARCHAR(32) NULL,
    d_created_at                DATETIME    NOT NULL DEFAULT GETDATE(),
    c_created_by                VARCHAR(32) NULL,
    d_updated_at                DATETIME NULL DEFAULT GETDATE(),
    c_updated_by                VARCHAR(32) NULL
);
