### Create Toyota ID (Success Case)
POST http://localhost:8080/api/v1/hcm/webhooks/toyota-id
Content-Type: application/json
X-API-Key: your-webhook-api-key
X-Signature: your-hmac-secret-key
X-Event-Id: d4d7402f-dcab-443d-a829-f1817085f8da
X-Event-Timestamp: 1708782696

{
  "process": "toyota id creation",
  "event_ID": "d4d7402f-dcab-443d-a829-f1817085f8da",
  "timestamp": 1731229200,
  "data": {
    "one_account": {
      "one_account_ID": "GMO4GNYBSI0D85IP6K59OYGJZ6VOKW3Y",
      "dealer_customer_ID": "ASTVAJMF00552",
      "first_name": "Nkoc",
      "last_name": "Maf",
      "phone_number": "081234567890",
      "email": "nkoc.maf@example.com",
      "birth_date": "1995-08-12",
      "verification_channel": "SMS",
      "ktp_number": "PRRJKAESWC086H",
      "occupation": "Engineer",
      "gender": "FEMALE",
      "address_label": "Rumah",
      "residence_address": "52EXP0ADG Q9G3AAD T, WI YktLIL ONb2 gSLTo a6pP YXZJ, NIl1n",
      "province": "DKI Jakarta",
      "city": "Jakarta Barat",
      "district": "Pulo Gadung",
      "subdistrict": "Jati",
      "postal_code": "13220",
      "detail_address": "gts89detiyt",
      "registration_channel": "MTOYOTA",
      "registration_datetime": 1731229200,
      "consent_given": true,
      "consent_given_at": 1731229200,
      "consent_given_during": "REGISTRATION",
      "toyota_single_ID_status": "ACTIVE",
      "customer_category": "INDIVIDUAL"
    },
    "customer_vehicle": {
      "primary_user": "MASTER",
      "vin": "MKFZKE81SCJ115045",
      "police_number": "B1234ABC",
      "katashiki_suffix": "NSP170R-MWYQKD02",
      "color_code": "59",
      "model": "Innova Zenix",
      "variant": "2.0 Q A/T",
      "color": "Putih",
      "stnk_number": "aVZGjcOK",
      "stnk_name": "uHwG2zT",
      "stnk_expiry_date": 1731229200,
      "stnk_address": "52EXP0ADG Q9G3AAD T, WI YktLIL ONb2 gSLTo a6pP YXZJ",
      "customer_type": [
        "BUYER",
        "OWNER"
      ],
      "vehicle_category": "RETAIL"
    }
  }
}
