// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handlers/engine/handler.go

// Package engine is a generated GoMock package.
package engine

import (
	context "context"
	reflect "reflect"

	engine "github.com/arraisi/hcm-be/internal/domain/dto/engine"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// RunMonthlySegmentation mocks base method.
func (m *MockService) RunMonthlySegmentation(ctx context.Context, request engine.RunMonthlySegmentationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMonthlySegmentation", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMonthlySegmentation indicates an expected call of RunMonthlySegmentation.
func (mr *MockServiceMockRecorder) RunMonthlySegmentation(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMonthlySegmentation", reflect.TypeOf((*MockService)(nil).RunMonthlySegmentation), ctx, request)
}
