// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package webhook is a generated GoMock package.
package webhook

import (
	context "context"
	reflect "reflect"

	domain "github.com/arraisi/hcm-be/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTestDriveService is a mock of TestDriveService interface.
type MockTestDriveService struct {
	ctrl     *gomock.Controller
	recorder *MockTestDriveServiceMockRecorder
}

// MockTestDriveServiceMockRecorder is the mock recorder for MockTestDriveService.
type MockTestDriveServiceMockRecorder struct {
	mock *MockTestDriveService
}

// NewMockTestDriveService creates a new mock instance.
func NewMockTestDriveService(ctrl *gomock.Controller) *MockTestDriveService {
	mock := &MockTestDriveService{ctrl: ctrl}
	mock.recorder = &MockTestDriveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestDriveService) EXPECT() *MockTestDriveServiceMockRecorder {
	return m.recorder
}

// CreateTestDriveBooking mocks base method.
func (m *MockTestDriveService) CreateTestDriveBooking(ctx context.Context, request domain.BookingEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestDriveBooking", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTestDriveBooking indicates an expected call of CreateTestDriveBooking.
func (mr *MockTestDriveServiceMockRecorder) CreateTestDriveBooking(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestDriveBooking", reflect.TypeOf((*MockTestDriveService)(nil).CreateTestDriveBooking), ctx, request)
}

// UpdateTestDriveBooking mocks base method.
func (m *MockTestDriveService) UpdateTestDriveBooking(ctx context.Context, request domain.BookingEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestDriveBooking", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTestDriveBooking indicates an expected call of UpdateTestDriveBooking.
func (mr *MockTestDriveServiceMockRecorder) UpdateTestDriveBooking(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestDriveBooking", reflect.TypeOf((*MockTestDriveService)(nil).UpdateTestDriveBooking), ctx, request)
}

// MockIdempotencyStore is a mock of IdempotencyStore interface.
type MockIdempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyStoreMockRecorder
}

// MockIdempotencyStoreMockRecorder is the mock recorder for MockIdempotencyStore.
type MockIdempotencyStoreMockRecorder struct {
	mock *MockIdempotencyStore
}

// NewMockIdempotencyStore creates a new mock instance.
func NewMockIdempotencyStore(ctrl *gomock.Controller) *MockIdempotencyStore {
	mock := &MockIdempotencyStore{ctrl: ctrl}
	mock.recorder = &MockIdempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyStore) EXPECT() *MockIdempotencyStoreMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockIdempotencyStore) Exists(eventID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", eventID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockIdempotencyStoreMockRecorder) Exists(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIdempotencyStore)(nil).Exists), eventID)
}

// Store mocks base method.
func (m *MockIdempotencyStore) Store(eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockIdempotencyStoreMockRecorder) Store(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockIdempotencyStore)(nil).Store), eventID)
}
