package domain

import (
	"time"

	"github.com/google/uuid"
)

type ServiceBookingPartItem struct {
	ID                   int64     `db:"i_id"`
	ServiceBookingPartID string    `db:"i_service_booking_part_id"`
	PartNumber           string    `db:"c_part_number"`
	PartName             string    `db:"n_part_name"`
	CreatedAt            time.Time `db:"d_created_at"`
	CreatedBy            string    `db:"c_created_by"`
	UpdatedAt            time.Time `db:"d_updated_at"`
	UpdatedBy            string    `db:"c_updated_by"`
}

// TableName returns the database table name for the ServiceBookingPartItem model
func (sbpi *ServiceBookingPartItem) TableName() string {
	return "dbo.tm_service_booking_part_items"
}

// Columns returns the list of database columns for the ServiceBookingPartItem model
func (sbpi *ServiceBookingPartItem) Columns() []string {
	return []string{
		"i_id",
		"i_service_booking_part_id",
		"c_part_number",
		"n_part_name",
		"d_created_at",
		"c_created_by",
		"d_updated_at",
		"c_updated_by",
	}
}

// SelectColumns returns the list of columns to select in queries for the ServiceBookingPartItem model
func (sbpi *ServiceBookingPartItem) SelectColumns() []string {
	return []string{
		"CAST(i_id AS NVARCHAR(36)) as i_id",
		"CAST(i_service_booking_part_id AS NVARCHAR(36)) as i_service_booking_part_id",
		"c_part_number",
		"n_part_name",
		"d_created_at",
		"c_created_by",
		"d_updated_at",
		"c_updated_by",
	}
}

// ToCreateMap prepares the columns and values for inserting a new ServiceBookingPartItem record
func (sbpi *ServiceBookingPartItem) ToCreateMap() ([]string, []interface{}) {
	columns := make([]string, 0, len(sbpi.Columns()))
	values := make([]interface{}, 0, len(sbpi.Columns()))

	// ID will be auto-generated by the database
	id := uuid.NewString()
	columns = append(columns, "i_id")
	values = append(values, id)

	if sbpi.ServiceBookingPartID != "" {
		columns = append(columns, "i_service_booking_part_id")
		values = append(values, sbpi.ServiceBookingPartID)
	}

	if sbpi.PartNumber != "" {
		columns = append(columns, "c_part_number")
		values = append(values, sbpi.PartNumber)
	}

	if sbpi.PartName != "" {
		columns = append(columns, "n_part_name")
		values = append(values, sbpi.PartName)
	}

	columns = append(columns, "d_created_at")
	values = append(values, sbpi.CreatedAt)

	columns = append(columns, "c_created_by")
	values = append(values, sbpi.CreatedBy)

	columns = append(columns, "d_updated_at")
	values = append(values, sbpi.UpdatedAt)

	columns = append(columns, "c_updated_by")
	values = append(values, sbpi.UpdatedBy)

	return columns, values
}

// ToUpdateMap prepares the columns and values for updating an existing ServiceBookingPartItem record
func (sbpi *ServiceBookingPartItem) ToUpdateMap() map[string]interface{} {
	updateMap := make(map[string]interface{})

	if sbpi.PartNumber != "" {
		updateMap["c_part_number"] = sbpi.PartNumber
	}

	if sbpi.PartName != "" {
		updateMap["n_part_name"] = sbpi.PartName
	}

	updateMap["d_updated_at"] = sbpi.UpdatedAt
	updateMap["c_updated_by"] = sbpi.UpdatedBy

	return updateMap
}
